const express = require("express");
const authRouter = require("./authRouter");
const documentRouter = require("./documentRouter");
const summaryRouter = require("./summaryRouter");
const quizRouter = require("./quizRouter");
const feedbackRouter = require("./feedbackRouter");
const explanationRouter = require("./explanationRouter");
const router = express.Router();
router.use("/user-auth", authRouter);
router.use("/document", documentRouter);
router.use("/summarize", summaryRouter);
router.use("/explain", explanationRouter);
router.use("/quiz", quizRouter);
router.use("/feedback", feedbackRouter);
module.exports = router;
