###
# ****************************************************************** TEST RUNNING ***************************************************************************
# Get("/pocketdoc/user-auth")

GET http://localhost:3000/pocketdoc/user-auth/


###
#******************************************************* SIGN UP *******************************************
# Post("/pocketdoc/user-auth/signup")
POST http://localhost:3000/pocketdoc/user-auth/signup
accept: application/json
content-type: application/json

{
  "username": "TestUser",
  "email": "test12@gmail.com",
  "password": "test123"
}

###
#******************************************************* SIGN IN *******************************************
# "_id": "676b8a4fe61f6f99a2050c82",
# Post("/pocketdoc/user-auth/signin")

POST http://localhost:3000/pocketdoc/user-auth/signin
accept: application/json
content-type: application/json

{
  "email": "test123@gmail.com",
  "password": "test123"
}

###
# POST("/pocketdoc/document/upload")
# @file-to-variable pdfUpload ./pdf_to_use.pdf binary
POST http://localhost:3000/pocketdoc/document/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryxyz123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI4YTRmZTYxZjZmOTlhMjA1MGM4MiIsImlhdCI6MTczNTQ2ODgxMX0.ZnxBhTysHTOJ6bOiAaKQ55Ml8DB-q6B4Eo5CxudT4bM


------WebKitFormBoundaryxyz123
Content-Disposition: form-data; name="file"; filename="document.pdf"
Content-Type: application/pdf

{{pdfUpload}}
------WebKitFormBoundaryxyz123
Content-Disposition: form-data; name="title"

My Document Title
------WebKitFormBoundaryxyz123--


###
## GET("/pocketdoc/document/")
GET http://localhost:3000/pocketdoc/document/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI4YTRmZTYxZjZmOTlhMjA1MGM4MiIsImlhdCI6MTczNTYzNTA5Mn0.ELy1bSeV_lJlLyJgZM5YEs2NHiyb7wqDM_mo3PNykMo

###
# GET("pocketdoc/document/:documentId")
#67712e93ac6d3b5aa6bc
GET http://localhost:3000/pocketdoc/document/6773aee4d9dc8839e5179966
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI4YTRmZTYxZjZmOTlhMjA1MGM4MiIsImlhdCI6MTczNTYzNTA5Mn0.ELy1bSeV_lJlLyJgZM5YEs2NHiyb7wqDM_mo3PNykMo
 
###
# GET("pocketdoc/document/:documentId/toc")
GET http://localhost:3000/pocketdoc/document/67712e93ac6d3b5aa6bc164a/toc
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI4YTRmZTYxZjZmOTlhMjA1MGM4MiIsImlhdCI6MTczNTYzNTA5Mn0.ELy1bSeV_lJlLyJgZM5YEs2NHiyb7wqDM_mo3PNykMo

###
 
