def get_quiz_prompt_from_chunk(text: str) -> str:
    return f"""
Based on the following text, generate 3 multiple-choice questions (MCQs):
{text}

Format:
QUESTION: ...
OPTIONS:
A. ...
B. ...
C. ...
D. ...
ANSWER: B
END
"""
